export default {
	KAWAII_STORE: process.env.REACT_APP_KAWAII_STORE_ADDRESS,
	FACTORY: process.env.REACT_APP_FACTORY_ADDRESS,
	KAWAII_TOKEN: process.env.REACT_APP_KAWAII_TOKEN_ADDRESS,
	KAWAIIVERSE_NFT1155: process.env.REACT_APP_KAWAIIVERSE_NFT1155_ADDRESS,
};
